/*
  # Add Comprehensive RSS Sources

  1. World News Sources
  2. Politics Sources  
  3. Business & Economy Sources
  4. Technology Sources
  5. Science & Environment Sources
  6. Health Sources
  7. War & Conflict Sources
  8. Breaking News Sources
  9. Entertainment Sources
  10. Sports Sources
  11. Current Events Sources

  All sources categorized and regionalized appropriately.
*/

-- World News Sources
INSERT INTO news_sources (name, url, rss_url, category, region, active) VALUES
('BBC World News', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/world/rss.xml', 'world', 'global', true),
('Al Jazeera All News', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/all.xml', 'world', 'global', true),
('Reuters World News', 'https://www.reuters.com', 'http://feeds.reuters.com/Reuters/worldNews', 'world', 'global', true),
('The Guardian World', 'https://www.theguardian.com', 'https://www.theguardian.com/world/rss', 'world', 'global', true),
('New York Times World', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'world', 'global', true),
('Washington Post World', 'https://www.washingtonpost.com', 'http://feeds.washingtonpost.com/rss/world', 'world', 'global', true),
('France24 English', 'https://www.france24.com', 'https://www.france24.com/en/rss', 'world', 'global', true),
('Deutsche Welle All News', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-en-all', 'world', 'global', true),
('CNN World News', 'https://www.cnn.com', 'https://rss.cnn.com/rss/edition_world.rss', 'world', 'global', true),
('Associated Press Top News', 'https://apnews.com', 'https://apnews.com/apf-topnews?format=feed', 'world', 'global', true),
('NBC World News', 'https://www.nbcnews.com', 'http://feeds.nbcnews.com/feeds/worldnews', 'world', 'global', true),
('South China Morning Post World', 'https://www.scmp.com', 'https://www.scmp.com/rss/world', 'world', 'asia', true),
('Global News World', 'https://globalnews.ca', 'https://globalnews.ca/world/feed/', 'world', 'global', true),
('ABC Australia World', 'https://www.abc.net.au', 'https://www.abc.net.au/news/feed/46182/rss.xml', 'world', 'global', true),
('Sydney Morning Herald World', 'https://www.smh.com.au', 'https://www.smh.com.au/rssheadlines/world.xml', 'world', 'global', true),
('LA Times World', 'https://www.latimes.com', 'https://www.latimes.com/world/rss2.0.xml', 'world', 'global', true),
('Yahoo News World', 'https://news.yahoo.com', 'http://news.yahoo.com/rss/world', 'world', 'global', true),
('Canada.com RSS', 'https://rss.canada.com', 'https://rss.canada.com/get/?F270', 'world', 'global', true),
('Times of India World', 'https://timesofindia.indiatimes.com', 'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms', 'world', 'asia', true),
('Sky News World', 'https://news.sky.com', 'http://feeds.skynews.com/feeds/rss/world.xml', 'world', 'global', true),

-- Politics Sources
('New York Times Politics', 'https://www.nytimes.com', 'http://rss.nytimes.com/services/xml/rss/nyt/Politics.xml', 'politics', 'us', true),
('CNN Politics', 'https://www.cnn.com', 'http://rss.cnn.com/rss/cnn_allpolitics.rss', 'politics', 'us', true),
('Reuters Politics', 'https://www.reuters.com', 'http://feeds.reuters.com/Reuters/PoliticsNews', 'politics', 'global', true),
('Politico', 'https://www.politico.com', 'https://www.politico.com/rss/politics08.xml', 'politics', 'us', true),
('Washington Post Politics', 'https://www.washingtonpost.com', 'http://feeds.washingtonpost.com/rss/politics', 'politics', 'us', true),
('NPR Politics', 'https://www.npr.org', 'https://rss.npr.org/1004/', 'politics', 'us', true),
('Fox News Politics', 'https://www.foxnews.com', 'http://feeds.foxnews.com/foxnews/politics', 'politics', 'us', true),
('BBC Politics', 'https://www.bbc.com', 'http://www.bbc.co.uk/news/politics/rss.xml', 'politics', 'uk', true),
('The Guardian Politics', 'https://www.theguardian.com', 'https://www.theguardian.com/politics/rss', 'politics', 'uk', true),
('New York Times Upshot', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Upshot.xml', 'politics', 'us', true),
('HuffPost Politics', 'https://www.huffpost.com', 'https://www.huffpost.com/section/politics/feed?format=xml', 'politics', 'us', true),
('Real Clear Politics', 'https://www.realclearpolitics.com', 'http://www.realclearpolitics.com/index.xml', 'politics', 'us', true),
('The Hill', 'https://thehill.com', 'https://www.thehill.com/rss/syndicator/19110', 'politics', 'us', true),
('National Review', 'https://www.nationalreview.com', 'https://www.nationalreview.com/rss/', 'politics', 'us', true),
('ProPublica Politics', 'https://www.propublica.org', 'https://feeds.propublica.org/propublica/politics', 'politics', 'us', true),
('Associated Press Politics', 'https://apnews.com', 'https://apnews.com/hub/politics?format=feed', 'politics', 'global', true),
('US News Politics', 'https://www.usnews.com', 'https://www.usnews.com/rss/news/politics', 'politics', 'us', true),

-- Business & Economy Sources
('BBC Business', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/business/rss.xml', 'business', 'global', true),
('Reuters Business', 'https://www.reuters.com', 'https://feeds.reuters.com/reuters/businessNews', 'business', 'global', true),
('CNN Business', 'https://www.cnn.com', 'http://rss.cnn.com/rss/edition_business.rss', 'business', 'global', true),
('Financial Times', 'https://www.ft.com', 'https://www.ft.com/?format=rss', 'business', 'global', true),
('Wall Street Journal', 'https://www.wsj.com', 'https://www.wsj.com/xml/rss/3_7031.xml', 'business', 'us', true),
('CNBC', 'https://www.cnbc.com', 'https://www.cnbc.com/id/10001147/device/rss/rss.html', 'business', 'us', true),
('The Economist Business', 'https://www.economist.com', 'https://www.economist.com/business-finance/rss.xml', 'business', 'global', true),
('Forbes Business', 'https://www.forbes.com', 'https://www.forbes.com/business/feed2/', 'business', 'us', true),
('MarketWatch', 'https://www.marketwatch.com', 'https://www.marketwatch.com/rss/topstories', 'business', 'us', true),
('StartupBeat', 'https://www.startupbeat.co', 'https://www.startupbeat.co/feed/', 'business', 'global', true),
('CoinDesk', 'https://www.coindesk.com', 'https://www.coindesk.com/feed/', 'business', 'global', true),
('The Verge Business', 'https://www.theverge.com', 'https://www.theverge.com/business/rss/index.xml', 'business', 'global', true),
('TechCrunch', 'https://techcrunch.com', 'https://techcrunch.com/feed/', 'business', 'global', true),
('Financial Times Companies', 'https://www.ft.com', 'https://www.ft.com/companies?format=rss', 'business', 'global', true),
('CNBC Markets', 'https://www.cnbc.com', 'https://www.cnbc.com/id/19854910/device/rss/rss.html', 'business', 'us', true),
('Reuters Markets', 'https://www.reuters.com', 'https://www.reuters.com/markets/rss.xml', 'business', 'global', true),
('Associated Press Business', 'https://apnews.com', 'https://apnews.com/hub/business?format=feed', 'business', 'global', true),
('NPR Business', 'https://www.npr.org', 'https://www.npr.org/rss/rss.php?id=1019', 'business', 'us', true),
('New York Times Economy', 'https://www.nytimes.com', 'http://rss.nytimes.com/services/xml/rss/nyt/Economy.xml', 'business', 'us', true),

-- Technology Sources
('TechCrunch', 'https://techcrunch.com', 'https://feeds.feedburner.com/TechCrunch/', 'technology', 'global', true),
('CNN Technology', 'https://www.cnn.com', 'http://rss.cnn.com/rss/edition_technology.rss', 'technology', 'global', true),
('Wired', 'https://www.wired.com', 'https://www.wired.com/feed/rss', 'technology', 'global', true),
('The Verge', 'https://www.theverge.com', 'https://www.theverge.com/rss/index.xml', 'technology', 'global', true),
('Ars Technica', 'https://arstechnica.com', 'https://rss.arstechnica.com/arstechnica/index/', 'technology', 'global', true),
('Engadget', 'https://www.engadget.com', 'https://www.engadget.com/rss.xml', 'technology', 'global', true),
('Gizmodo', 'https://gizmodo.com', 'https://feeds.gizmodo.com/gizmodo/full', 'technology', 'global', true),
('CNET', 'https://www.cnet.com', 'https://www.cnet.com/rss/news/', 'technology', 'global', true),
('ZDNet', 'https://www.zdnet.com', 'https://www.zdnet.com/news/rss.xml', 'technology', 'global', true),
('Mashable', 'https://mashable.com', 'https://feeds.feedburner.com/mashable', 'technology', 'global', true),
('TechRadar', 'https://www.techradar.com', 'https://www.techradar.com/rss', 'technology', 'global', true),
('CSO Online', 'https://www.csoonline.com', 'https://www.csoonline.com/index.rss', 'technology', 'global', true),
('Space.com', 'https://www.space.com', 'https://www.space.com/feeds/all', 'technology', 'global', true),
('CyberScoop', 'https://www.cyberscoop.com', 'https://www.cyberscoop.com/feed/', 'technology', 'global', true),
('Slashdot', 'https://slashdot.org', 'https://www.slashdot.org/Slashdot/slashdot.rss', 'technology', 'global', true),
('Nature AI', 'https://www.nature.com', 'https://www.nature.com/subjects/artificial-intelligence.rss', 'technology', 'global', true),
('Scientific American Tech', 'https://www.scientificamerican.com', 'https://www.scientificamerican.com/rss/tech.xml', 'technology', 'global', true),
('ZDNet Security', 'https://www.zdnet.com', 'https://www.zdnet.com/topic/security/rss.xml', 'technology', 'global', true),
('The Guardian Technology', 'https://www.theguardian.com', 'https://www.theguardian.com/technology/rss', 'technology', 'global', true),
('NPR Technology', 'https://www.npr.org', 'https://rss.npr.org/1019/rss.xml', 'technology', 'us', true),

-- Science & Environment Sources
('BBC Science & Environment', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/science_and_environment/rss.xml', 'science', 'global', true),
('New York Times Science', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml', 'science', 'global', true),
('Science Daily', 'https://www.sciencedaily.com', 'https://www.sciencedaily.com/rss/all.xml', 'science', 'global', true),
('Nature', 'https://www.nature.com', 'https://www.nature.com/nature.rss', 'science', 'global', true),
('Scientific American', 'https://www.scientificamerican.com', 'https://www.sciam.com/feed/', 'science', 'global', true),
('EurekAlert', 'https://www.eurekalert.org', 'https://www.eurekalert.org/rss.xml', 'science', 'global', true),
('NASA Breaking News', 'https://www.nasa.gov', 'https://www.nasa.gov/rss/dyn/breaking_news.rss', 'science', 'global', true),
('Climate Change News', 'https://www.climatechangenews.com', 'https://www.climatechangenews.com/feed/', 'science', 'global', true),
('The Guardian Environment', 'https://www.theguardian.com', 'https://www.theguardian.com/environment/rss', 'science', 'global', true),
('National Geographic Environment', 'https://www.nationalgeographic.com', 'https://www.nationalgeographic.com/environment/rss/', 'science', 'global', true),
('Live Science', 'https://www.livescience.com', 'https://www.livescience.com/home/feed/site.xml', 'science', 'global', true),
('NPR Science', 'https://www.npr.org', 'https://www.npr.org/rss/rss.php?id=1007', 'science', 'us', true),
('Deutsche Welle Science', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-en-science', 'science', 'global', true),
('Energy Post', 'https://www.energypost.eu', 'https://www.energypost.eu/feed/', 'science', 'global', true),
('UNEP', 'https://www.unep.org', 'https://www.unep.org/feed', 'science', 'global', true),
('TreeHugger', 'https://www.treehugger.com', 'https://feeds.feedburner.com/treehugger', 'science', 'global', true),
('Climate.gov', 'https://www.climate.gov', 'https://www.climate.gov/news-feeds', 'science', 'global', true),
('Reuters Science', 'https://www.reuters.com', 'https://feeds.reuters.com/reuters/scienceNews', 'science', 'global', true),
('Associated Press Science', 'https://apnews.com', 'https://apnews.com/hub/science?format=feed', 'science', 'global', true),

-- Health Sources
('BBC Health', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/health/rss.xml', 'health', 'global', true),
('CNN Health', 'https://www.cnn.com', 'https://rss.cnn.com/rss/edition_health.rss', 'health', 'global', true),
('New York Times Health', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Health.xml', 'health', 'global', true),
('WHO News', 'https://www.who.int', 'https://www.who.int/news-room/rss/en/', 'health', 'global', true),
('NPR Health', 'https://www.npr.org', 'https://www.npr.org/rss/rss.php?id=1128', 'health', 'us', true),
('NIH News', 'https://www.nih.gov', 'https://www.nih.gov/rss.xml', 'health', 'us', true),
('Medical News Today', 'https://www.medicalnewstoday.com', 'https://www.medicalnewstoday.com/rss', 'health', 'global', true),
('Harvard Health', 'https://www.health.harvard.edu', 'https://www.health.harvard.edu/rss.xml', 'health', 'us', true),
('WebMD', 'https://www.webmd.com', 'https://www.webmd.com/rss/rss.aspx', 'health', 'us', true),
('Forbes Health', 'https://www.forbes.com', 'https://www.forbes.com/health/feed2/', 'health', 'us', true),
('Associated Press Health', 'https://apnews.com', 'https://apnews.com/hub/health?format=feed', 'health', 'global', true),
('STAT News', 'https://www.statnews.com', 'https://www.statnews.com/feed/', 'health', 'us', true),
('CDC Blogs', 'https://blogs.cdc.gov', 'https://blogs.cdc.gov/feed/', 'health', 'us', true),
('Psychology Today', 'https://www.psychologytoday.com', 'https://www.psychologytoday.com/intl/blog/feed.xml', 'health', 'global', true),
('Mayo Clinic', 'https://www.mayoclinic.org', 'https://www.mayoclinic.org/feed.xml', 'health', 'us', true),
('Nature Public Health', 'https://www.nature.com', 'https://www.nature.com/subjects/public-health.rss', 'health', 'global', true),
('Science Daily Health', 'https://www.sciencedaily.com', 'https://www.sciencedaily.com/rss/health.xml', 'health', 'global', true),
('CIDRAP', 'https://www.cidrap.umn.edu', 'https://www.cidrap.umn.edu/rss/home-feed.xml', 'health', 'us', true),
('Deutsche Welle Health', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-en-health', 'health', 'global', true),
('Reuters Health', 'https://www.reuters.com', 'https://www.reuters.com/news/archive/healthNews?format=xml', 'health', 'global', true),

-- War & Conflict Sources
('BBC Middle East', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/world/middle_east/rss.xml', 'politics', 'middle-east', true),
('Al Jazeera Middle East', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/middleeast.xml', 'politics', 'middle-east', true),
('Reuters World News', 'https://www.reuters.com', 'https://www.reuters.com/rssFeed/worldNews', 'politics', 'global', true),
('New York Times World', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'politics', 'global', true),
('Associated Press Middle East', 'https://apnews.com', 'https://apnews.com/hub/middle-east?format=feed', 'politics', 'middle-east', true),
('The Guardian Middle East', 'https://www.theguardian.com', 'https://www.theguardian.com/world/middleeast/rss', 'politics', 'middle-east', true),
('Deutsche Welle Middle East', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-en-middleeast', 'politics', 'middle-east', true),
('Defense.gov', 'https://www.defense.gov', 'https://www.defense.gov/News/RSS/', 'politics', 'us', true),
('War on the Rocks', 'https://warontherocks.com', 'https://feeds.feedburner.com/waronthrocks', 'politics', 'global', true),
('Radio Free Europe Middle East', 'https://www.rferl.org', 'https://www.rferl.org/api/zmg/rss/rss2.xml?category=middle-east', 'politics', 'middle-east', true),
('Jerusalem Post', 'https://www.jpost.com', 'https://www.jpost.com/Rss/RssFeedsHeadlines.aspx', 'politics', 'middle-east', true),
('AL-Monitor', 'https://www.al-monitor.com', 'https://www.al-monitor.com/rss/all.xml', 'politics', 'middle-east', true),
('Chatham House', 'https://www.chathamhouse.org', 'https://www.chathamhouse.org/media/rss.xml', 'politics', 'global', true),
('Crisis Group', 'https://www.crisisgroup.org', 'https://www.crisisgroup.org/rss.xml', 'politics', 'global', true),
('Human Rights Watch', 'https://www.hrw.org', 'https://www.hrw.org/rss/feeds/news.xml', 'politics', 'global', true),
('UN OCHA', 'https://www.unocha.org', 'https://www.unocha.org/rss.xml', 'politics', 'global', true),
('PBS NewsHour Middle East', 'https://www.pbs.org', 'https://rss.pbs.org/newshour/middle_east/rss.xml', 'politics', 'middle-east', true),
('France24 Middle East', 'https://www.france24.com', 'https://www.france24.com/en/middle-east/rss', 'politics', 'middle-east', true),
('Reuters UK Video', 'https://www.reuters.com', 'http://feeds.reuters.com/Reuters/UKVideoNews', 'politics', 'global', true),
('NPR World', 'https://www.npr.org', 'https://rss.npr.org/1004/', 'politics', 'global', true),

-- Breaking News Sources
('CNN Latest', 'https://www.cnn.com', 'http://rss.cnn.com/rss/cnn_latest.rss', 'general', 'global', true),
('BBC Breaking', 'https://www.bbc.com', 'http://feeds.bbci.co.uk/news/rss.xml', 'general', 'global', true),
('Reuters Top News', 'https://www.reuters.com', 'https://www.reuters.com/rssFeed/topNews', 'general', 'global', true),
('Associated Press Breaking', 'https://apnews.com', 'https://apnews.com/apf-topnews?format=feed', 'general', 'global', true),
('ABC News Top Stories', 'https://abcnews.go.com', 'http://feeds.abcnews.com/abcnews/topstories', 'general', 'us', true),
('Yahoo News Top Stories', 'https://news.yahoo.com', 'http://rss.news.yahoo.com/rss/topstories', 'general', 'global', true),
('NPR Latest', 'https://www.npr.org', 'https://feeds.npr.org/1001/rss.xml', 'general', 'us', true),
('Newsy', 'https://www.newsy.com', 'https://feeds.feedburner.com/newsy', 'general', 'us', true),
('The Guardian Breaking', 'https://www.theguardian.com', 'https://www.theguardian.com/world/rss', 'general', 'global', true),
('CBS News Latest', 'https://www.cbsnews.com', 'http://feeds.cbsnews.com/latest/rss/main', 'general', 'us', true),
('Deutsche Welle Breaking', 'https://www.dw.com', 'https://rss.dw.com/rdf/rss-generic', 'general', 'global', true),
('Al Jazeera Breaking', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/all.xml', 'general', 'global', true),
('New York Times Breaking', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'general', 'us', true),
('Canada.com Breaking', 'https://rss.canada.com', 'https://rss.canada.com/get/?F7497', 'general', 'global', true),
('Sky News Breaking', 'https://news.sky.com', 'http://feeds.skynews.com/feeds/rss/home.xml', 'general', 'global', true),
('SMH National', 'https://www.smh.com.au', 'https://feeds.smh.com.au/rssheadlines/national.xml', 'general', 'global', true),
('Fox News Latest', 'https://www.foxnews.com', 'http://feeds.foxnews.com/foxnews/latest?format=xml', 'general', 'us', true),
('Washington Post Breaking', 'https://www.washingtonpost.com', 'http://feeds.washingtonpost.com/rss/rss_homepage', 'general', 'us', true),
('Vice News', 'https://www.vice.com', 'http://feeds.vice.com/rss/index.xml', 'general', 'global', true),
('RSS.com Blog', 'https://rss.com', 'https://rss.com/blog/feed', 'general', 'global', true),

-- Entertainment Sources
('Entertainment Tonight', 'https://www.etonline.com', 'https://www.etonline.com/rss', 'entertainment', 'us', true),
('Hollywood Reporter', 'https://www.hollywoodreporter.com', 'https://www.hollywoodreporter.com/t/headlines/feed/', 'entertainment', 'us', true),
('Billboard', 'https://www.billboard.com', 'https://www.billboard.com/feed/', 'entertainment', 'us', true),
('Variety', 'https://variety.com', 'https://variety.com/feed/', 'entertainment', 'us', true),
('Rolling Stone Music', 'https://www.rollingstone.com', 'https://www.rollingstone.com/music/music-news/feed/', 'entertainment', 'us', true),
('Entertainment Weekly', 'https://ew.com', 'https://feeds.feedburner.com/ew/allnews', 'entertainment', 'us', true),
('Vulture', 'https://www.vulture.com', 'https://www.vulture.com/rss/index.xml', 'entertainment', 'us', true),
('NME Music', 'https://www.nme.com', 'https://www.nme.com/news/music/feed', 'entertainment', 'global', true),
('IndieWire', 'https://www.indiewire.com', 'https://www.indiewire.com/c/entertainment/feed/', 'entertainment', 'us', true),
('Deadline', 'https://deadline.com', 'https://deadline.com/feed/', 'entertainment', 'us', true),
('TMZ', 'https://www.tmz.com', 'https://www.tmz.com/rss.xml', 'entertainment', 'us', true),
('Digital Spy Entertainment', 'https://www.digitalspy.com', 'https://www.digitalspy.com/rss/entertainment/', 'entertainment', 'global', true),
('CinemaBlend', 'https://www.cinemablend.com', 'https://www.cinemablend.com/rss/all.xml', 'entertainment', 'us', true),
('GameSpot', 'https://www.gamespot.com', 'https://www.gamespot.com/feeds/news/', 'entertainment', 'global', true),
('Polygon', 'https://www.polygon.com', 'https://www.polygon.com/rss/index.xml', 'entertainment', 'us', true),
('IMDb Celebrity News', 'https://www.imdb.com', 'https://www.imdb.com/news/celebrity/rss', 'entertainment', 'global', true),
('Fandango News', 'https://www.fandango.com', 'https://www.fandango.com/rss/news.xml', 'entertainment', 'us', true),
('Star Wars News', 'https://www.starwars.com', 'https://www.starwars.com/news/feed', 'entertainment', 'global', true),
('Empire Online', 'https://www.empireonline.com', 'https://www.empireonline.com/feeds/all', 'entertainment', 'global', true),

-- Sports Sources
('ESPN', 'https://www.espn.com', 'https://www.espn.com/espn/rss/news', 'sports', 'us', true),
('Sky Sports', 'https://www.skysports.com', 'https://www.skysports.com/rss/12040', 'sports', 'uk', true),
('Sportsnet', 'https://www.sportsnet.ca', 'https://www.sportsnet.ca/feed/', 'sports', 'global', true),
('CBS Sports', 'https://www.cbssports.com', 'https://www.cbssports.com/rss/headlines/', 'sports', 'us', true),
('BBC Sport', 'https://www.bbc.com', 'https://feeds.bbci.co.uk/sport/rss.xml?edition=uk', 'sports', 'uk', true),
('NFL', 'https://www.nfl.com', 'https://www.nfl.com/rss/rsslanding?searchString=home', 'sports', 'us', true),
('NBA', 'https://www.nba.com', 'https://www.nba.com/rss/nba_rss.xml', 'sports', 'us', true),
('MLB', 'https://www.mlb.com', 'https://www.mlb.com/feeds/news/rss.xml', 'sports', 'us', true),
('NHL', 'https://www.nhl.com', 'https://www.nhl.com/rss/news.xml', 'sports', 'us', true),
('Golf Channel', 'https://www.golfchannel.com', 'https://www.golfchannel.com/rss-feeds', 'sports', 'us', true),
('Tennis.com', 'https://www.tennis.com', 'https://www.tennis.com/rss/all.xml', 'sports', 'global', true),
('FIFA', 'https://www.fifa.com', 'https://www.fifa.com/rss/index.xml', 'sports', 'global', true),
('Olympic', 'https://www.olympic.org', 'https://www.olympic.org/news/rss.xml', 'sports', 'global', true),
('RTE Sport', 'https://www.rte.ie', 'https://www.rte.ie/sport/rss.xml', 'sports', 'global', true),
('Sports Illustrated', 'https://www.si.com', 'https://www.si.com/rss/si_topstories.rss', 'sports', 'us', true),
('NBC Sports', 'https://www.nbcsports.com', 'https://www.nbcsports.com/feeds/news', 'sports', 'us', true),
('Formula 1', 'https://www.formula1.com', 'https://www.f1.com/rss/news.xml', 'sports', 'global', true),
('Sky Sports F1', 'https://www.skysports.com', 'https://www.skysports.com/rss/11095', 'sports', 'global', true),
('WWE', 'https://www.wwe.com', 'https://www.wwe.com/feeds/rss', 'sports', 'us', true),
('Cricbuzz', 'https://www.cricbuzz.com', 'https://www.cricbuzz.com/rss-news.xml', 'sports', 'asia', true),

-- Current Events Sources
('BBC World Current Events', 'https://www.bbc.com', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'general', 'global', true),
('CNN World Current Events', 'https://www.cnn.com', 'http://rss.cnn.com/rss/edition_world.rss', 'general', 'global', true),
('New York Times World Current Events', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'general', 'global', true),
('Al Jazeera Current Events', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/all.xml', 'general', 'global', true),
('Reuters World Current Events', 'https://www.reuters.com', 'https://www.reuters.com/rssFeed/worldNews', 'general', 'global', true),
('The Guardian World Current Events', 'https://www.theguardian.com', 'https://www.theguardian.com/world/rss', 'general', 'global', true),
('Associated Press World', 'https://apnews.com', 'https://apnews.com/hub/world/rss', 'general', 'global', true),
('NBC World Current Events', 'https://www.nbcnews.com', 'https://www.nbcnews.com/news/world/rss', 'general', 'global', true),
('France24 Current Events', 'https://www.france24.com', 'https://www.france24.com/en/rss', 'general', 'global', true),
('Sky News World Current Events', 'https://news.sky.com', 'https://feeds.skynews.com/feeds/rss/world.xml', 'general', 'global', true),
('Global News Current Events', 'https://globalnews.ca', 'https://globalnews.ca/world/feed/', 'general', 'global', true),
('Time Magazine', 'https://time.com', 'https://time.com/feed/', 'general', 'global', true),
('Yahoo News World Current Events', 'https://news.yahoo.com', 'https://news.yahoo.com/rss/world', 'general', 'global', true),
('Washington Post World Current Events', 'https://www.washingtonpost.com', 'https://www.washingtonpost.com/world/feed/', 'general', 'global', true),
('CBC World', 'https://www.cbc.ca', 'https://www.cbc.ca/cmlink/rss-world', 'general', 'global', true),
('Independent World', 'https://www.independent.co.uk', 'https://www.independent.co.uk/news/world/rss', 'general', 'global', true),
('Bloomberg World', 'https://www.bloomberg.com', 'https://www.bloomberg.com/feed/podcast/world.xml', 'general', 'global', true),
('Times of India World Current Events', 'https://timesofindia.indiatimes.com', 'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms', 'general', 'asia', true),
('NDTV World', 'https://www.ndtv.com', 'https://feeds.feedburner.com/ndtvnews-world-news', 'general', 'asia', true),
('Euronews World', 'https://www.euronews.com', 'https://www.euronews.com/rss?level=world', 'general', 'global', true),
('Voice of America', 'https://www.voanews.com', 'https://www.voanews.com/rss', 'general', 'global', true),
('The Hill Current Events', 'https://thehill.com', 'https://thehill.com/rss/syndicator/19110', 'general', 'us', true),
('Politico World', 'https://www.politico.com', 'https://www.politico.com/rss/world-news', 'general', 'global', true),
('Japan Times World', 'https://www.japantimes.co.jp', 'https://www.japantimes.co.jp/feed/world/', 'general', 'asia', true),
('Straits Times World', 'https://www.straitstimes.com', 'https://www.straitstimes.com/rss/world', 'general', 'asia', true),
('Deutsche Welle Current Events', 'https://www.dw.com', 'https://rss.dw.com/xml/rss-en-all', 'general', 'global', true),
('SCMP Current Events', 'https://www.scmp.com', 'https://www.scmp.com/rss/91/feed', 'general', 'asia', true),
('ABC News International', 'https://abcnews.go.com', 'https://abcnews.go.com/abcnews/internationalheadlines', 'general', 'global', true),
('Voice of America Current Events', 'https://www.voanews.com', 'https://www.voanews.com/rss', 'general', 'global', true),
('Telegraph', 'https://www.telegraph.co.uk', 'https://www.telegraph.co.uk/rss.xml', 'general', 'global', true),
('The Economist International', 'https://www.economist.com', 'https://www.economist.com/international/rss.xml', 'general', 'global', true),
('NPR World Current Events', 'https://www.npr.org', 'https://www.npr.org/rss/rss.php?id=1004', 'general', 'global', true),
('Newsweek', 'https://www.newsweek.com', 'https://www.newsweek.com/rss', 'general', 'global', true),
('LA Times World Current Events', 'https://www.latimes.com', 'https://www.latimes.com/world/rss2.0.xml', 'general', 'global', true),
('AL-Monitor Current Events', 'https://www.al-monitor.com', 'https://www.al-monitor.com/rss', 'general', 'middle-east', true),
('Jerusalem Post Current Events', 'https://www.jpost.com', 'https://www.jpost.com/Rss/RssFeedsHeadlines.aspx', 'general', 'middle-east', true),
('Financial Times Current Events', 'https://www.ft.com', 'https://www.ft.com/?format=rss', 'general', 'global', true),
('Sky News Australia', 'https://www.skynews.com.au', 'https://www.skynews.com.au/rss', 'general', 'global', true),
('The Hindu International', 'https://www.thehindu.com', 'https://www.thehindu.com/news/international/feeder/default.rss', 'general', 'asia', true),
('BuzzFeed World', 'https://www.buzzfeednews.com', 'https://www.buzzfeednews.com/world.xml', 'general', 'global', true)

ON CONFLICT (rss_url) DO NOTHING;